#!/bin/bash
set -eEuo pipefail

export VAULT_ADDR=https://vault.dide.ic.ac.uk:8200
VAULT_TOKEN=$(vault login -method=github -token-only)
export VAULT_TOKEN

hdb_username=$(vault read -field=username "secret/certbot-hdb/credentials")
hdb_password=$(vault read -field=password "secret/certbot-hdb/credentials")
hdb_credentials_file=.hdb-credentials

cat >$hdb_credentials_file <<EOF
HDB_ACME_USERNAME=$hdb_username
HDB_ACME_PASSWORD=$hdb_password
EOF

echo "Wrote $hdb_credentials_file"
