apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - ../../base

replicas:
  - count: 9
    name: shiny-deploy

labels:
  - includeSelectors: true
    pairs:
      env: production
patches:
  - path: persistence-patch.yaml # if 1 node cluster remove this patch which enables longhorn
  - path: ingress-patch.yaml
