#!/usr/bin/env bash
VOLUME=twinkle_apps
HERE=$(realpath $(dirname $0))
echo $HERE
docker volume create $VOLUME
docker run --rm \
       -v $VOLUME:/apps \
       -v $HERE:/src:ro \
       instrumentisto/rsync-ssh \
       rsync -a --delete /src/ /apps/
docker run --rm \
       -v $VOLUME:/apps:ro \
       instrumentisto/rsync-ssh \
       tree /apps
