apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
metadata:
  name: shiny

namespace: twinkle # assume this namespace exists

resources:
  - persistance.yaml
  - deployment.yaml
  - service.yaml
  - ingress.yaml
