# todo: storage capacity as per requirements
# can use local-path if single node or dont need distributed & replicated
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: shiny-pvc
spec:
  storageClassName: longhorn
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 15Gi
